INSERT INTO `gadgets` (`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES
(2, 'iphone 6s', 1, 'Weight	143 g,Nano-SIM,camera 12 MP, f/2.2, 29mm, phase detection autofocus, ios-9,Siri natural language commands and dictation,iCloud cloud service,Improves upon the s6s already successful design.Improved image quality and auto focus speed. Added IP68 protection and the micro SD reader. Bigger battery. Ships with Marshmallow. More powerful chipset. ', 656, 'images/apple-iphone-6s-plus.jpg', 'Girl', 9),
(3, 'iphone 7', 1, 'Weight	139 g,Nano-SIM,Water resistant up to 1 meter and 30 minutes, camera 12MP, f/2.2, 32mm, phase detection autofocus, ios-10.0.1,Siri natural language commands and dictation,iCloud cloud service,MP3/WAV/AAX+/AIFF/Apple Lossless player', 750, 'images/iphone7.jpg', 'Girl', 9);
INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (4,'Dell i5559',2,'15.6-inch Full HD touchscreen,Intel Core i5-6200U,8GB memory/1TB HDD,i5/i7,1 TBhard drive,8gb DDR3L 1600 MHz,Intel RealSense 3D camera',449,'images/delli5559.jpg','girl',45), 
(5,'Dell i5559',2,'13-inch Full HD touchscreen, 6th Generation Intel® Core™ i3-6100U Processor,4GB memory,500GB hard drive, 13.3-inch FHD (1920 x 1080) Truelife LED-Backlit Touch Display with Wide Viewing Angles-HD Camera,Intel RealSense 3D camera',549,'images/dell13touch.jpg','girl',85);
INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (6,'google pixel',3,'5.0 inches FHD AMOLED at 441ppi,2.5D Corning® Gorilla® Glass 4 Size:5.6 x 2.7 x 0.2 ~ 0.3 inches Battery:2,770 mAh battery,4GB LPDDR4 RAM,32 or 128GB,Camera:12.3MP,Large 1.55μm pixels',849,'images/googlepixel.jpg','girl',45),
 (7,'samsung galaxy s7',3,'Display 5.1"2560 x 1440 pixels,Size and Weight:5.61 x 2.74 x 0.31 inches,5.36 ounces,Operating System and Processor:Android 6.0 Marshmallow Qualcomm® Snapdragon™ 820 processor,Camera:12 MP Rear Facing Camera,5MP Front Facing Camera,Memory:4GB RAM,32GB ROM, expandable up to 256GB',629,'images/samsunggalaxys7.jpg','girl',85)
 INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (8,'canon powershot',4,'1/2.3" CMOS sensor:Captures high-resolution images up to 4608 x 3456 pixels.
50x optical/4x digital/200x total zoom,3" LCD
With a screen resolution of 461,000 dots allows you to easily frame subjects and view information, even from a wide angle.
1080p Full HD video,DIGIC 4+ image processor,Intelligent IS,Scene modes,Hybrid Auto,Zoom Framing Assist.',289,'images/canonpowershot.jpg','girl',45), 
(9,'DD3300 Nikon ',4,'DX format,24.2 Mega pixels, 5 FPS continous shooting,100-12800 ISO,Full HD 1080',449,'images/nikond300dlsr.jpg','girl',85);
INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (10,'Avast anti virus',5,'Intelligent anti virus,cyber capture,smart scan, browser cleanup,secure DNS, passwords,firewall, anti spam,home network security',59,'images/avast.jpg','girl',45), 
(11,'Kaspersky',5,'hybrid protection,real time protection, anti blocker, url advisor,two way fire wall, system blocker,anti phishing,secure keyboard, privacy protection,web protection, anti theft protection',49,'images/kaspersky.jpg','girl',85)
INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (13,' Bluetooth Wireless Headset With Mic',6,'13.4 x 8.1 x 2.3 inches,Item Weight 1.1 pounds,Durable Construction And Innovative, Advanced Technology,Incomparably Long Lasting Battery Life And Countless Functions By The Touch Of A Button ',59,'images/bose.jpg','girl',65), 
(12,'ipod',6,'Siri — Use your voice to send messages, set reminders, and more Use hands-free Listen and identify songs,Built-in rechargeable lithium-ion battery,Music playback time: Up to 40 hours,Weight: 3.10 ounces (88 grams)2,Maps: Location-based service3,1080p HD video recording (30 fps),Camera:1.2MP photos',199,'images/ipod.jpg','girl',75)
INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (14,'Seagate hard disk',7,'Sleek, metal design for everywhere portability.Includes 200GB of cloud storage,Time Machine compatible,Quick file transfer with USB 3.0 connectivity,USB powered –no power supply necessary',69,'images/seagateharddisk.jpg','girl',45),
 (15,'Avera 32 inch Tv',7,'Display Size:32 inches Resolution:720 p,Connectivity Technology:No,Model Year:2015,Display Technology:LED',109,'images/AveraTv.jpg','girl',85),
 (16,'Lg Electronic 60 inch Tv',7,'Display Size:60 inches,Resolution:3840 x 2160,Connectivity Technology:Built-in Wi-Fi,Model Year:2016,Display Technology:LED',109,'images/Lg electronicTv1.jpg','girl',25)
 INSERT INTO `gadgets`(`itemid`, `itemname`, `categoryId`, `itemdesc`, `price`, `image`, `Gender`, `quantity`) VALUES (17,'suface studio Pc',8,'
6th Gen Intel Core i5, 8GB RAM, 1TB Rapid hybrid drive,Ultra-thin 28-inch adjustable PixelSense Display, NVIDIA GeForce GTX 965M 2GB GPU GDDR5 memory, Including Surface Pen Surface Keyboard Surface Mouse, Windows 10 Pro,Item Weight	21.1 pounds, Product Dimensions	25.1 x 0.4 x 17.1 inches',2569,'images/surfacestudiopc.jpg','girl',45),
 (18,'Dell opti plex Pc',8,'Display Size:19.0 inches,Computer Memory Size:8.0 GB,Hardware Platform:PC,System Ram Type:ddr3 sdram,Cpu Model Manufacturer:Intel
',3309,'images/delloptiplexpc.jpg','girl',85);
